# MongoDB
MONGODB_CONNECTION_STRING = 'localhost'
MONGODB_DATABASE_NAME = 'default'
MONGODB_UPSERT = True
MONGODB_COLLECTION_NAME_FIELD = 'mongodb_collection_name'
MONGODB_COLLECTION_NAME_DEFAULT = 'default'
MONGODB_ITEM_PRIMARY_KEY_FIELD = 'primary_key'
MONGODB_ITEM_PRIMARY_KEY_DEFAULT = 'id'
